defaults:
  - model: catboost        # config/model/catboost.yaml 로드
  - registry         # config/model_registry.yaml 로드
  - _self_

device : cpu

seed : 42

id_label : ID
target_label : completed

train_csv : data/raw/train.csv
inference_csv : data/raw/test.csv
log_dir : log/

need_valid : True
valid_ratio : 0.2

do_inference : True